name: Kilat 10s

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Ambil file terakhir saja agar ngebut

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Generate Sitemap & Push
        run: |
          node main.js
          git config --global user.name "Robot Kilat"
          git config --global user.email "robot@fast.com"
          git add sitemap.xml robots.txt
          git commit -m "Auto sitemap 10s" || echo "No changes"
          git push
