name: Fast Smart Deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Ambil kode terbaru
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Node.js versi 24 terbaru (bebas peringatan deprecated)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # 3. Jalankan main.js (Perbaikan HTML, Sitemap, & Robots.txt)
      - name: Run main.js Smart Fixer
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Execute Script
        run: node main.js

      # 4. Validasi Error Internal (Memastikan file utama aman sebelum disebar)
      - name: Validate Files
        run: |
          echo "Memeriksa file utama..."
          if [ ! -f "index.html" ]; then
            echo "ERROR: index.html tidak ditemukan!"
            exit 1
          fi
          echo "Semua file lengkap dan aman."

      # 5. Konfigurasi dan Upload ke GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
