name: Update Result Kilat

on:
  push:
    branches: ["main"]
    paths:
      - 'result/*.js'  # Robot hanya bangun kalau ada file di folder result yang berubah
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-result:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ambil riwayat agar tidak conflict saat push

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Commit & Push Update Result
        run: |
          git config --global user.name "Robot Result Kilat"
          git config --global user.email "bot@fast-result.com"
          git add result/*.js
          git commit -m "Update result: $(date +'%Y-%m-%d %H:%M:%S')" || echo "Tidak ada perubahan"
          git push
