name: Generate Automated Sitemap 2026

on:
  push:
    branches:
      - main    # Ganti jadi master jika branch utama Anda bernama master
  workflow_dispatch:

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate Sitemap Robot
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate XML Sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://tunggalpaito.online
        drop-html-extension: true
        include-pdf: false

    - name: Create Automated Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Automated sitemap update"
        title: "🤖 Automated Sitemap Update"
        body: "Sitemap otomatis diperbarui oleh robot GitHub Actions versi terbaru."
        branch: "sitemap-updates"
        base: "main"

